from django.test import TestCase
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

class loginModelTest(TestCase):
    def setUp(self):
        pass